### ISSUE TITLE
All modules have stopped working

### ISSUE THREAD

**Issue by ChrisWiegman** [example42/puppet-modules#49]
With the latest Ubuntu/trusty64 box all example42 modules fail with errors similar to the following:

default: Wrapped exception:
==> default: Received incomplete information - no value provided for parameter my_class

This is true on APT, PHP and Apache (the 3 I am using) and for seemingly all default params on these modules

**Comment by ricciocri** [comment]
Hello Chris,
Which version of puppet are you using on that box ?

**Comment by alvagante** [comment]
Reverting https://github.com/example42/puppi/pull/124 should have restored the previous condition.
